### ISSUE TITLE
When using the "(" key, the game thinks that you are using the up arrow.

### ISSUE THREAD

**Issue by DanielDees** [DanielDees/TheRealmProjectTesting#11]
This caused some issues when I tested out someone who might type in something like

Selling SPD (1 Def)

the game thought that the "(" was an up arrow so it deleted what I had typed and sent me to the last thing I submitted.

**Comment by shryme** [comment]
Never saw this! Will look into it!

**Comment by shryme** [comment]
See #12 ! I just added a validation with the shift key!
